# Copyright (c) 2025-2026 Greg Ames/Ames & Associates. Licensed under the Coffee Right License — see LICENSE.
# Project: Terminal Switcher | Filename: FUNDING.yml
custom: ["https://buymeacoffee.com/terminalswitcher"]
